In [ ]:
import eigenpy as ei # type: ignore
# 可以理解为 c++ 的numpy

In [4]:
import numpy as np
import time

# 定义矩阵大小
MATRIX_SIZE = 50

def main():
    # 创建一个 2x3 的浮点数矩阵
    matrix_23 = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

    # 创建一个 3x1 的向量
    v_3d = np.array([3, 2, 1], dtype=float)
    vd_3d = np.array([4, 5, 6], dtype=float)

    # 输出矩阵
    print("matrix_23:")
    print(matrix_23)

    # 访问矩阵元素
    print("\n访问矩阵元素:")
    for i in range(2):
        for j in range(3):
            print(f"{matrix_23[i, j]}\t", end="")
        print()

    # 矩阵和向量相乘
    result = np.dot(matrix_23, v_3d)
    print("\n矩阵和向量相乘:")
    print(result)

    result2 = np.dot(matrix_23, vd_3d)
    print(result2)

    # 创建一个 3x3 的随机矩阵
    matrix_33 = np.random.rand(3, 3)
    print("\n随机 3x3 矩阵:")
    print(matrix_33)

    # 矩阵运算
    print("\n转置:")
    print(matrix_33.T)
    print("\n各元素和:", matrix_33.sum())
    print("迹:", np.trace(matrix_33))
    print("\n数乘:")
    print(10 * matrix_33)
    print("\n逆:")
    print(np.linalg.inv(matrix_33))
    print("\n行列式:", np.linalg.det(matrix_33))

    # 特征值和特征向量
    eigenvalues, eigenvectors = np.linalg.eig(np.dot(matrix_33.T, matrix_33))
    print("\n特征值:")
    print(eigenvalues)
    print("\n特征向量:")
    print(eigenvectors)

    # 解方程
    matrix_NN = np.random.rand(MATRIX_SIZE, MATRIX_SIZE)
    v_Nd = np.random.rand(MATRIX_SIZE, 1)

    # 直接求逆
    start_time = time.time()
    x = np.dot(np.linalg.inv(matrix_NN), v_Nd)
    end_time = time.time()
    print(f"\n直接求逆用时: {(end_time - start_time) * 1000:.2f} ms")

    # 使用 numpy 的线性代数求解器
    start_time = time.time()
    x = np.linalg.solve(matrix_NN, v_Nd)
    end_time = time.time()
    print(f"使用线性代数求解器用时: {(end_time - start_time) * 1000:.2f} ms")

if __name__ == "__main__":
    main()


matrix_23:
[[1. 2. 3.]
 [4. 5. 6.]]

访问矩阵元素:
1.0	2.0	3.0	
4.0	5.0	6.0	

矩阵和向量相乘:
[10. 28.]
[32. 77.]

随机 3x3 矩阵:
[[0.59072909 0.030378   0.9082771 ]
 [0.91017917 0.26572592 0.25185528]
 [0.89864733 0.78165028 0.64629743]]

转置:
[[0.59072909 0.91017917 0.89864733]
 [0.030378   0.26572592 0.78165028]
 [0.9082771  0.25185528 0.64629743]]

各元素和: 5.283739603654807
迹: 1.5027524427768877

数乘:
[[5.90729089 0.30378003 9.08277099]
 [9.10179173 2.65725921 2.51855276]
 [8.98647327 7.81650283 6.46297433]]

逆:
[[-0.06227341  1.71100852 -0.57924571]
 [-0.89703631 -1.07677377  1.6802615 ]
 [ 1.17148928 -1.07679944  0.32053467]]

行列式: 0.40345902306005893

特征值:
[3.4881225  0.13205673 0.35338376]

特征向量:
[[ 0.74008436  0.62118674 -0.25768617]
 [ 0.37338211 -0.69822387 -0.61079393]
 [ 0.55933973 -0.35582363  0.74868458]]

直接求逆用时: 2.50 ms
使用线性代数求解器用时: 0.04 ms


In [5]:
import numpy as np
import time

# 定义矩阵大小
MATRIX_SIZE = 50

def main():
    # 创建一个 2x3 的浮点数矩阵
    matrix_23 = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

    # 创建一个 3x1 的向量
    v_3d = np.array([3, 2, 1], dtype=float)
    vd_3d = np.array([4, 5, 6], dtype=float)

    # 输出矩阵
    print("matrix_23:")
    print(matrix_23)

    # 访问矩阵元素
    print("\n访问矩阵元素:")
    for i in range(2):
        for j in range(3):
            print(f"{matrix_23[i, j]}\t", end="")
        print()

    # 矩阵和向量相乘
    result = np.dot(matrix_23, v_3d)
    print("\n矩阵和向量相乘:")
    print(result)

    result2 = np.dot(matrix_23, vd_3d)
    print(result2)

    # 创建一个 3x3 的随机矩阵
    matrix_33 = np.random.rand(3, 3)
    print("\n随机 3x3 矩阵:")
    print(matrix_33)

    # 矩阵运算
    print("\n转置:")
    print(matrix_33.T)
    print("\n各元素和:", matrix_33.sum())
    print("迹:", np.trace(matrix_33))
    print("\n数乘:")
    print(10 * matrix_33)
    print("\n逆:")
    print(np.linalg.inv(matrix_33))
    print("\n行列式:", np.linalg.det(matrix_33))

    # 特征值和特征向量
    eigenvalues, eigenvectors = np.linalg.eig(np.dot(matrix_33.T, matrix_33))
    print("\n特征值:")
    print(eigenvalues)
    print("\n特征向量:")
    print(eigenvectors)

    # 解方程
    matrix_NN = np.random.rand(MATRIX_SIZE, MATRIX_SIZE)
    v_Nd = np.random.rand(MATRIX_SIZE, 1)

    # 直接求逆
    start_time = time.time()
    x = np.dot(np.linalg.inv(matrix_NN), v_Nd)
    end_time = time.time()
    print(f"\n直接求逆用时: {(end_time - start_time) * 1000:.2f} ms")

    # 使用 numpy 的线性代数求解器
    start_time = time.time()
    x = np.linalg.solve(matrix_NN, v_Nd)
    end_time = time.time()
    print(f"使用线性代数求解器用时: {(end_time - start_time) * 1000:.2f} ms")

if __name__ == "__main__":
    main()


matrix_23:
[[1. 2. 3.]
 [4. 5. 6.]]

访问矩阵元素:
1.0	2.0	3.0	
4.0	5.0	6.0	

矩阵和向量相乘:
[10. 28.]
[32. 77.]

随机 3x3 矩阵:
[[0.13818715 0.65205147 0.31598985]
 [0.43316487 0.71295849 0.72743794]
 [0.68286775 0.70454548 0.1557579 ]]

转置:
[[0.13818715 0.43316487 0.68286775]
 [0.65205147 0.71295849 0.70454548]
 [0.31598985 0.72743794 0.1557579 ]]

各元素和: 4.522960894849922
迹: 1.0069035381060414

数乘:
[[1.38187146 6.52051465 3.15989848]
 [4.33164871 7.12958487 7.27437943]
 [6.8286775  7.0454548  1.55757905]]

逆:
[[-2.40360688  0.72484071  1.49102376]
 [ 2.57011335 -1.16302761  0.21764987]
 [-1.08768874  2.08294727 -1.1011722 ]]

行列式: 0.1670257299887227

特征值:
[2.50113167 0.19899347 0.05605203]

特征向量:
[[-0.47747643 -0.64542404  0.5961913 ]
 [-0.74946094 -0.05499272 -0.65976064]
 [-0.45861156  0.76184225  0.45746238]]

直接求逆用时: 0.30 ms
使用线性代数求解器用时: 0.13 ms
